---
title: 'CAS - Seminární práce'
subtitle: 'Návštevnost plavecké haly ____'
author: 'Eliška Junková, Matěj Sloup'
date: "`r Sys.Date()`"
output: html_document
---

# Úvod do práce
Práce obsahuje základní analýzu návštevnosti a tržby plavecké haly, zahrnující analýzu trendu a extrapolace pokračování trendu.

# Načtení dat

<!-- Načtení knihoven-->
``` {r dataread-libs, include=FALSE}
library(dplyr)
library(lubridate)
```

<!-- Načtení dat-->
``` {r dataread-read, include=FALSE}
# U tohohle formátu nefunguje runnování jako řádek, ale dá se runovat celá buňka so idc
data <- read.table(
  "vystup-test.csv",
  header = FALSE,
  sep = ",",
  quote = "",
  fill = TRUE,
  dec = ",",
  stringsAsFactors = FALSE
)
```

<!-- Manipulace dat -->
``` {r dataread-format, include=FALSE}
data <- data %>%
  mutate(
    datum = dmy(V1),
    pocet_navstev = as.integer(V2),
    trzba = as.integer(gsub("[^0-9]", "", iconv(V3, "UTF-8", "ASCII", sub = "")))
  ) %>%
  select(datum, pocet_navstev, trzba)

data <- data %>%
  mutate(pocet_navstev = ifelse(pocet_navstev <= 1, NA, pocet_navstev))
data <- data %>%
  mutate(trzba = ifelse(trzba <= 1, NA, trzba))
```

<!-- Print dat -->
``` {r dataread-out, echo=FALSE}
head(data)
```
Formát datumu je ROK-MĚSÍC-DEN. Tržba je uvedena v CZK.

# Vizualizace
``` {r basicvisual-libs, include=FALSE}
library(ggplot2)
```

``` {r basicvisual, echo=FALSE}
# Graf pro hodnotu 1
ggplot(data, aes(x = datum, y = pocet_navstev)) +
  geom_line(color = "steelblue", linewidth = 1) +
  labs(title = "Časová řada - návštěvnost", x = "Datum", y = "počet návštěv") +
  theme_minimal()

# Graf pro hodnotu 2
ggplot(data, aes(x = datum, y = trzba)) +
  geom_line(color = "darkorange", linewidth = 1) +
  labs(title = "Časová řada - tržby", x = "Datum", y = "trzba") +
  theme_minimal()
```
